package com.poc.moneywithdawalapprovalproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MoneyWithdrawal implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Global Data")
	private com.lab.globaldata.GlobalData pjDGlobalData;
	@org.kie.api.definition.type.Label("Withdrawal Amount")
	private java.lang.Integer amount;

	@org.kie.api.definition.type.Label(value = "Single approval process for Users ")
	private java.lang.Boolean singleApproval;

	@org.kie.api.definition.type.Label(value = "Dual approval process for managers")
	private java.lang.Boolean managerApproval;

	@org.kie.api.definition.type.Label(value = "Overall Approval")
	private java.lang.Boolean approval;

	public MoneyWithdrawal() {
	}

	public com.lab.globaldata.GlobalData getPjDGlobalData() {
		return this.pjDGlobalData;
	}

	public void setPjDGlobalData(com.lab.globaldata.GlobalData pjDGlobalData) {
		this.pjDGlobalData = pjDGlobalData;
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public java.lang.Boolean getSingleApproval() {
		return this.singleApproval;
	}

	public void setSingleApproval(java.lang.Boolean singleApproval) {
		this.singleApproval = singleApproval;
	}

	public java.lang.Boolean getManagerApproval() {
		return this.managerApproval;
	}

	public void setManagerApproval(java.lang.Boolean managerApproval) {
		this.managerApproval = managerApproval;
	}

	public java.lang.Boolean getApproval() {
		return this.approval;
	}

	public void setApproval(java.lang.Boolean approval) {
		this.approval = approval;
	}

	public MoneyWithdrawal(com.lab.globaldata.GlobalData pjDGlobalData,
			java.lang.Integer amount, java.lang.Boolean singleApproval,
			java.lang.Boolean managerApproval, java.lang.Boolean approval) {
		this.pjDGlobalData = pjDGlobalData;
		this.amount = amount;
		this.singleApproval = singleApproval;
		this.managerApproval = managerApproval;
		this.approval = approval;
	}

}